services:
  neo4j:
    container_name: neo4j
    image: neo4j:5.26.21-enterprise
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=eval

      - NEO4J_server_memory_heap_initial__size=2G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=2G
      - server.jvm.additional=-XX:+UseZGC
      - server.jvm.additional=-XX:+UnlockExperimentalVMOptions
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
